version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "07:00"
    timezone: Japan
  open-pull-requests-limit: 10
  reviewers:
  - Tsuuko
